@ECHO OFF
SET choc=choco install -y
@powershell -NoProfile -ExecutionPolicy unrestricted -Command "iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))" && SET PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin
chocolatey update
%choc% 7zip.install
%choc% adblockplusie
%choc% adobereader
%choc% adobeshockwaveplayer
%choc% android-sdk
%choc% calibre
%choc% cameyo
%choc% ccleaner
%choc% ccenhancer
%choc% chocolatey
%choc% chocolateygui
%choc% classic-shell
%choc% cmder.portable
%choc% combofix
%choc% cpu-z
%choc% cygwin
%choc% everything
%choc% filebot
%choc% filezilla
%choc% firefox
%choc% adblockplusfirefox
%choc% flashplayerplugin
%choc% flashplayeractivex
%choc% foxitreader
%choc% githubforwindows
%choc% gimp
%choc% googlechrome
%choc% adblockpluschrome
%choc% grepwin
%choc% hitmanproportable_x64
%choc% hitmanproportable_x86
%choc% httrack
%choc% imgburn
%choc% javaruntime
%choc% jdk8
%choc% jre8
%choc% malwarebytes
%choc% notepadplusplus.install
%choc% pip
%choc% plexmediaserver
%choc% putty
%choc% python
%choc% recuva
%choc% revo.uninstaller
%choc% rkillportable
%choc% rmprepusb
%choc% rufus
%choc% seleniumiedriver
%choc% speccy
%choc% superantispyware
%choc% synergy
%choc% sysinternals
%choc% tdsskillerportable
%choc% teamviewer
%choc% testdisk
%choc% thunderbird
%choc% tightvnc
%choc% tor-browser
%choc% unetbootin
%choc% universal-usb-installer
%choc% virtualbox
%choc% virtualbox.extensionpack
%choc% vlc
%choc% vuzeclient
%choc% wget
%choc% wincommandpaste
%choc% windbg
%choc% windirstat
%choc% wim2vhd
%choc% wudt
%choc% yumi
chocolatey update all
