@ECHO OFF
SET choc=choco install -y
@powershell -NoProfile -ExecutionPolicy unrestricted -Command "iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))" && SET PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin
chocolatey update
%choc% 7zip.install
%choc% adblockplusie
%choc% adobereader
%choc% adobeshockwaveplayer
%choc% calibre
%choc% cameyo
%choc% ccleaner
%choc% chocolatey
%choc% chocolateygui
%choc% classic-shell
%choc% filezilla
%choc% firefox
%choc% adblockplusfirefox
%choc% flashplayerplugin
%choc% flashplayeractivex
%choc% githubforwindows
%choc% gimp
%choc% googlechrome
%choc% adblockpluschrome
%choc% httrack
%choc% imgburn
%choc% javaruntime
%choc% notepadplusplus.install
%choc% pip
%choc% putty
%choc% python
%choc% recuva
%choc% revo.uninstaller
%choc% rmprepusb
%choc% seleniumiedriver
%choc% synergy
%choc% sysinternals
%choc% teamviewer
%choc% thunderbird
%choc% tor-browser
%choc% virtualbox
%choc% virtualbox.extensionpack
%choc% vlc
%choc% wincommandpaste
%choc% windirstat
%choc% wim2vhd
chocolatey update all
